// Generated by Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if defined(__has_attribute) && __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import CoreData;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

SWIFT_CLASS("_TtC18CapillaryFramework13AsterSecureBO")
@interface AsterSecureBO : NSObject
@property (nonatomic) NSInteger loyalty_points;
@property (nonatomic) NSInteger fltExpired;
@property (nonatomic) NSInteger fltRedeemed;
@property (nonatomic) NSInteger fltAdjusted;
@property (nonatomic) NSInteger fltReturned;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CoreDataAccessLayer;
@class CartItemBO;
@class CategoryBO;

SWIFT_CLASS("_TtC18CapillaryFramework6BaseBL")
@interface BaseBL : NSObject
@property (nonatomic, strong) CoreDataAccessLayer * _Nonnull data_layer;
- (NSInteger)getSupportIdWithArrayWithArr:(NSArray<CartItemBO *> * _Nonnull)arr parentID:(NSString * _Nonnull)parentID SWIFT_WARN_UNUSED_RESULT;
- (void)saveCategoriesInDbWithArr:(NSArray<CategoryBO *> * _Nonnull)arr;
- (NSString * _Nullable)convertDictionaryToStringWithDict:(NSDictionary<NSString *, NSString *> * _Nonnull)dict SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nullable)convertStringToDictionary:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)encodeSpecialCharactersManually:(NSString * _Nonnull)strParam SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)convertSpecialCharactersFromStringForAddress:(NSString * _Nonnull)strParam SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)convertStringFromSpecialCharactersWithStrParam:(NSString * _Nonnull)strParam SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework6Banner")
@interface Banner : BaseBL
- (void)getAllBannersWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework9BannersBO")
@interface BannersBO : NSObject
@property (nonatomic) NSInteger StoreID;
@property (nonatomic, copy) NSString * _Nonnull BrandID;
@property (nonatomic, copy) NSString * _Nonnull CityID;
@property (nonatomic, copy) NSString * _Nonnull itemid;
@property (nonatomic, copy) NSString * _Nonnull itemtype;
@property (nonatomic, copy) NSString * _Nonnull BrandTagID;
@property (nonatomic, copy) NSString * _Nonnull CategoryID;
@property (nonatomic, copy) NSString * _Nonnull ContentType;
@property (nonatomic, copy) NSString * _Nonnull ContentUrl;
@property (nonatomic, copy) NSString * _Nonnull Description;
@property (nonatomic, copy) NSString * _Nonnull Height;
@property (nonatomic, copy) NSString * _Nonnull HostingProvider;
@property (nonatomic, copy) NSString * _Nonnull IsTargetNewPage;
@property (nonatomic, copy) NSString * _Nonnull RefCode;
@property (nonatomic, copy) NSString * _Nonnull ReferenceType;
@property (nonatomic, copy) NSString * _Nonnull TargetID;
@property (nonatomic, copy) NSString * _Nonnull TargetType;
@property (nonatomic, copy) NSString * _Nonnull Thumbnail;
@property (nonatomic, copy) NSString * _Nonnull Width;
@property (nonatomic, copy) NSString * _Nonnull EndDate;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class BundleProductItemBO;

SWIFT_CLASS("_TtC18CapillaryFramework13BundleGroupBO")
@interface BundleGroupBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull bundlegroupid;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic) BOOL isrequired;
@property (nonatomic) BOOL isprimarygroup;
@property (nonatomic, copy) NSString * _Nonnull position;
@property (nonatomic, copy) NSString * _Nonnull minquantity;
@property (nonatomic) BOOL ismultiselect;
@property (nonatomic, copy) NSString * _Nonnull inputtype;
@property (nonatomic, copy) NSArray<BundleProductItemBO *> * _Nonnull arrItems;
@property (nonatomic) BOOL isOpened;
@property (nonatomic, copy) NSString * _Nonnull h2CategoryName;
@property (nonatomic) NSInteger Inventory;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework19BundleProductItemBO")
@interface BundleProductItemBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull bundleitemid;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull minquantity;
@property (nonatomic, copy) NSString * _Nonnull overriddenprice;
@property (nonatomic) BOOL isincludedinbundleprice;
@property (nonatomic, copy) NSString * _Nonnull position;
@property (nonatomic, copy) NSString * _Nonnull mrp;
@property (nonatomic, copy) NSString * _Nonnull webprice;
@property (nonatomic, copy) NSString * _Nonnull inventory;
@property (nonatomic, copy) NSString * _Nonnull largeimage;
@property (nonatomic, copy) NSString * _Nonnull smallimage;
@property (nonatomic, copy) NSString * _Nonnull description1;
@property (nonatomic) BOOL isdefault;
@property (nonatomic, copy) NSString * _Nonnull variantProducts;
@property (nonatomic, copy) NSString * _Nonnull productid;
@property (nonatomic, copy) NSString * _Nonnull variantproductid;
@property (nonatomic) BOOL isuserdefinedqty;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nonnull variants;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework3CRM")
@interface CRM : BaseBL
- (void)getCustomerDataFromCRMWithMobileNumberWithMobileNo:(NSString * _Nonnull)mobileNo successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getStoresDataFromCRMWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getSecurePointsWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UserProfileBO;
@class NSDate;

SWIFT_CLASS("_TtC18CapillaryFramework21CapillaryUserDefaults")
@interface CapillaryUserDefaults : NSObject
+ (BOOL)getLoginStatus SWIFT_WARN_UNUSED_RESULT;
+ (void)setLoginStatusWithObject:(BOOL)object;
+ (BOOL)getIsLastOrderAvailable SWIFT_WARN_UNUSED_RESULT;
+ (void)setIsLastOrderAvailableWithObject:(BOOL)object;
+ (BOOL)getIsShopOnline SWIFT_WARN_UNUSED_RESULT;
+ (void)setIsShopOnlineWithObject:(BOOL)object;
+ (void)setUserNameWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getUserName SWIFT_WARN_UNUSED_RESULT;
+ (void)setCountryCodeWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getCountryCode SWIFT_WARN_UNUSED_RESULT;
+ (void)setStoreNameWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getStoreName SWIFT_WARN_UNUSED_RESULT;
+ (void)setCurrencyWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getAccessToken SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getOTPToken SWIFT_WARN_UNUSED_RESULT;
+ (void)setOTPTokenWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getCurrency SWIFT_WARN_UNUSED_RESULT;
+ (void)setExtensionCodeWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getExtensionCode SWIFT_WARN_UNUSED_RESULT;
+ (void)setLastOrderIdWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getLastOrderId SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserEMailWithObject:(NSString * _Nonnull)object;
+ (void)setUserPasswordWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getUserPassword SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getUserEMail SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getStoreId SWIFT_WARN_UNUSED_RESULT;
+ (void)setMinOrderAmountWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getUserMobile SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserMobileWithObject:(NSString * _Nonnull)object;
+ (void)setStoreIdWithObject:(NSString * _Nonnull)object;
+ (void)setStoreAddressWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getStoreAddress SWIFT_WARN_UNUSED_RESULT;
+ (void)setCityIdWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getcityId SWIFT_WARN_UNUSED_RESULT;
+ (void)setStoreAreaWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getStoreArea SWIFT_WARN_UNUSED_RESULT;
+ (void)setStoreDeliveryModeWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getStoreDeliveryMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setUserIdWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getUserId SWIFT_WARN_UNUSED_RESULT;
+ (void)setAccessTokenWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getImagePath SWIFT_WARN_UNUSED_RESULT;
+ (void)setImagePathWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getBannerImagePath SWIFT_WARN_UNUSED_RESULT;
+ (void)setBannerImagePathWithObject:(NSString * _Nonnull)object;
+ (void)setAboutUsWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getAboutUs SWIFT_WARN_UNUSED_RESULT;
+ (void)setPasswordLengthWithObject:(NSInteger)object;
+ (NSInteger)getPasswordLength SWIFT_WARN_UNUSED_RESULT;
+ (void)setMobileNoLengthWithObject:(NSInteger)object;
+ (NSInteger)getMobileNoLength SWIFT_WARN_UNUSED_RESULT;
+ (void)setMobileNoStartWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getMobileNoStart SWIFT_WARN_UNUSED_RESULT;
+ (void)setuserFirstNameWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nullable)getuserFirstName SWIFT_WARN_UNUSED_RESULT;
+ (void)setuserLastNameWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)getuserLastName SWIFT_WARN_UNUSED_RESULT;
+ (void)setShippngModeWithObject:(NSString * _Nonnull)object;
+ (NSString * _Nonnull)GetShippngMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setDeliverySlotIDWithObject:(NSString * _Nullable)object;
+ (NSString * _Nonnull)getDeliverySlotID SWIFT_WARN_UNUSED_RESULT;
+ (void)setConfigValueWithValue:(id _Nonnull)value key:(NSString * _Nonnull)key;
+ (id _Nonnull)getConfigValueWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
+ (void)removeUseProfile;
+ (void)setUserProfileWithObjProfile:(UserProfileBO * _Nonnull)objProfile;
+ (UserProfileBO * _Nullable)getUserProfile SWIFT_WARN_UNUSED_RESULT;
+ (void)setLoginDate:(NSDate * _Nonnull)object;
+ (NSDate * _Nonnull)getLoginDate SWIFT_WARN_UNUSED_RESULT;
+ (void)setTimeSlotDate:(NSDate * _Nonnull)object;
+ (NSDate * _Nonnull)getTimeSlotDate SWIFT_WARN_UNUSED_RESULT;
+ (void)setDeliverySlotWithObjDeliverySlot:(NSDictionary<NSString *, NSString *> * _Nullable)objDeliverySlot;
+ (NSDictionary<NSString *, NSString *> * _Nullable)getDeliverySlot SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ShipingAddressBO;
@class CartTable;

SWIFT_CLASS("_TtC18CapillaryFramework4Cart")
@interface Cart : BaseBL
- (void)sendRequestForOTPWithMobileNum:(NSString * _Nonnull)mobileNum countryCode:(NSString * _Nonnull)countryCode successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)setDeliverySlotWithSlotID:(NSString * _Nonnull)slotID SlotDate:(NSString * _Nonnull)SlotDate successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getAvaliableShipingSlotsWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)removeVocherServiceWithVoucherText:(NSString * _Nonnull)voucherText successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)addCartProductsToServerWithArrProduct:(NSArray<CartItemBO *> * _Nonnull)arrProduct isIndiaServer:(BOOL)isIndiaServer isPickUp:(BOOL)isPickUp currencyCode:(NSString * _Nonnull)currencyCode stateName:(NSString * _Nonnull)stateName successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)setShippingOptionsWithModeIdWithStrModeId:(NSString * _Nonnull)strModeId successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)updateItemFromCartWithProduct:(CartItemBO * _Nonnull)product successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)removeItemFromCartWithProduct:(CartItemBO * _Nonnull)product successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)callApplyVocharServiceWithVoucherText:(NSString * _Nonnull)voucherText successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)updateCartAddressWithObjectWithBo:(ShipingAddressBO * _Nonnull)bo successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)removeAllCartItemsFromOnlyServerWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)doCartOperationWithOperation:(NSString * _Nonnull)operation product:(CartTable * _Nonnull)product successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getCartItemsWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)removeSelectedCartItemsWithArrProduct:(NSArray<CartItemBO *> * _Nonnull)arrProduct currencyCode:(NSString * _Nonnull)currencyCode isIndiaServer:(BOOL)isIndiaServer successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getShippingModeWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework6CartBO")
@interface CartBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull Bill_Address1;
@property (nonatomic, copy) NSString * _Nonnull Bill_Address2;
@property (nonatomic, copy) NSString * _Nonnull Bill_CityName;
@property (nonatomic, copy) NSString * _Nonnull Bill_CountryCode;
@property (nonatomic, copy) NSString * _Nonnull Bill_Email;
@property (nonatomic, copy) NSString * _Nonnull Bill_FirstName;
@property (nonatomic, copy) NSString * _Nonnull Bill_LastName;
@property (nonatomic, copy) NSString * _Nonnull Bill_StateCode;
@property (nonatomic, copy) NSString * _Nonnull Bill_Telephone;
@property (nonatomic, copy) NSString * _Nonnull ErrorCollection;
@property (nonatomic, copy) NSString * _Nonnull GiftMsg;
@property (nonatomic, copy) NSString * _Nonnull IsShippingAddressDiffernt;
@property (nonatomic, copy) NSString * _Nonnull MerchantId;
@property (nonatomic, copy) NSString * _Nonnull OrderTotal;
@property (nonatomic, copy) NSString * _Nonnull ProductCost;
@property (nonatomic, copy) NSString * _Nonnull PromotionDiscount;
@property (nonatomic, copy) NSString * _Nonnull Ship_CityName;
@property (nonatomic, copy) NSString * _Nonnull Ship_Address2;
@property (nonatomic, copy) NSString * _Nonnull Ship_CountryCode;
@property (nonatomic, copy) NSString * _Nonnull Ship_Address1;
@property (nonatomic, copy) NSString * _Nonnull Ship_Email;
@property (nonatomic, copy) NSString * _Nonnull Ship_FirstName;
@property (nonatomic, copy) NSString * _Nonnull Ship_LastName;
@property (nonatomic, copy) NSString * _Nonnull Ship_PostCode;
@property (nonatomic, copy) NSString * _Nonnull Ship_StateCode;
@property (nonatomic, copy) NSString * _Nonnull Ship_Telephone;
@property (nonatomic, copy) NSString * _Nonnull ShippingCost;
@property (nonatomic, copy) NSString * _Nonnull ShippingModes;
@property (nonatomic, copy) NSString * _Nonnull TaxAmount;
@property (nonatomic, copy) NSString * _Nonnull VoucherCode;
@property (nonatomic, copy) NSString * _Nonnull VoucherDiscount;
@property (nonatomic, copy) NSString * _Nonnull Country;
@property (nonatomic, copy) NSString * _Nonnull UserSelectedCurrency;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nonnull arrSuppliers;
@property (nonatomic, copy) NSArray<CartItemBO *> * _Nonnull arrCartItem;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nonnull arrPaymentOptions;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nonnull arrShipingOptions;
@property (nonatomic, copy) NSArray<CartItemBO *> * _Nonnull arrFailedProducts;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework10CartItemBO")
@interface CartItemBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull Quantity;
@property (nonatomic, copy) NSString * _Nonnull descriptionn;
@property (nonatomic, copy) NSString * _Nonnull brand;
@property (nonatomic) NSInteger cartCount;
@property (nonatomic) float cartOldPrice;
@property (nonatomic, copy) NSString * _Nonnull CartReferenceKey;
@property (nonatomic, copy) NSString * _Nonnull cat1;
@property (nonatomic, copy) NSString * _Nonnull cat2;
@property (nonatomic, copy) NSString * _Nonnull cat3;
@property (nonatomic, copy) NSString * _Nonnull catalogpromotionDiscount;
@property (nonatomic, copy) NSString * _Nonnull catalogSequence;
@property (nonatomic) float ItemPromotionDiscountAmount;
@property (nonatomic) NSInteger inventory;
@property (nonatomic) BOOL isLabelShow;
@property (nonatomic) BOOL isSynced;
@property (nonatomic) BOOL isSelected;
@property (nonatomic, copy) NSString * _Nonnull MRP;
@property (nonatomic, copy) NSString * _Nonnull ProductId;
@property (nonatomic, copy) NSString * _Nonnull productTitle;
@property (nonatomic, copy) NSString * _Nonnull smallImage;
@property (nonatomic, copy) NSString * _Nonnull storeId;
@property (nonatomic, copy) NSString * _Nonnull SupplierId;
@property (nonatomic, copy) NSString * _Nonnull variantProductId;
@property (nonatomic, copy) NSString * _Nonnull variantProperty;
@property (nonatomic, copy) NSString * _Nonnull variantValue;
@property (nonatomic, copy) NSString * _Nonnull WebPrice;
@property (nonatomic, copy) NSString * _Nonnull dealId;
@property (nonatomic, copy) NSString * _Nonnull parentId;
@property (nonatomic, copy) NSString * _Nonnull parentCatTitle;
@property (nonatomic, copy) NSString * _Nonnull productType;
@property (nonatomic, copy) NSArray<BundleProductItemBO *> * _Nonnull arrBundleItem;
@property (nonatomic, copy) NSString * _Nonnull localCartReferenceKey;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("CartTable")
@interface CartTable : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;

@interface CartTable (SWIFT_EXTENSION(CapillaryFramework))
@property (nonatomic, copy) NSString * _Nullable cartReferenceKey;
@property (nonatomic, strong) NSNumber * _Nullable inventory;
@property (nonatomic, copy) NSString * _Nullable localReferenceKey;
@property (nonatomic, copy) NSString * _Nullable mrp;
@property (nonatomic, copy) NSString * _Nullable parentCatTitle;
@property (nonatomic, copy) NSString * _Nullable parentId;
@property (nonatomic, copy) NSString * _Nullable productId;
@property (nonatomic, copy) NSString * _Nullable productTitle;
@property (nonatomic) int16_t quantity;
@property (nonatomic, copy) NSString * _Nullable smallImage;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable varientProductId;
@property (nonatomic, copy) NSString * _Nullable webPrice;
@property (nonatomic, copy) NSString * _Nullable varientProperty;
@property (nonatomic, copy) NSString * _Nullable varientValue;
@property (nonatomic, copy) NSString * _Nullable cappedRefKey;
@property (nonatomic, copy) NSString * _Nullable priceCapped;
@property (nonatomic) int16_t totalCap;
@property (nonatomic) int16_t catalogpromotionDiscount;
@property (nonatomic, copy) NSString * _Nullable bundleCartReferenceKey;
@property (nonatomic) BOOL isPrimaryProduct;
@property (nonatomic) int16_t itemPromotionDiscountAmount;
@property (nonatomic) BOOL isPromotionProduct;
@property (nonatomic) BOOL isDefaultBundleItem;
@end


SWIFT_CLASS("_TtC18CapillaryFramework10CategoryBO")
@interface CategoryBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull level1;
@property (nonatomic, copy) NSString * _Nonnull leveltype;
@property (nonatomic, copy) NSString * _Nonnull level2;
@property (nonatomic, copy) NSString * _Nonnull level3;
@property (nonatomic, copy) NSString * _Nonnull level4;
@property (nonatomic, copy) NSString * _Nonnull level1_Id;
@property (nonatomic, copy) NSString * _Nonnull level2_Id;
@property (nonatomic, copy) NSString * _Nonnull level3_Id;
@property (nonatomic, copy) NSString * _Nonnull level4_Id;
@property (nonatomic) NSInteger displaySequence;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework12CategoryMenu")
@interface CategoryMenu : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface CategoryMenu (SWIFT_EXTENSION(CapillaryFramework))
@property (nonatomic, strong) NSNumber * _Nullable dataSequence;
@property (nonatomic, copy) NSString * _Nullable level1;
@property (nonatomic, copy) NSString * _Nullable level1_Id;
@property (nonatomic, copy) NSString * _Nullable level2;
@property (nonatomic, copy) NSString * _Nullable level2_Id;
@property (nonatomic, copy) NSString * _Nullable level3;
@property (nonatomic, copy) NSString * _Nullable level3_Id;
@property (nonatomic, copy) NSString * _Nullable leveltype;
@end


SWIFT_CLASS("_TtC18CapillaryFramework15CompareAttribBO")
@interface CompareAttribBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull Name;
@property (nonatomic, copy) NSString * _Nonnull Value;
@property (nonatomic, copy) NSString * _Nonnull Group;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework6Config")
@interface Config : BaseBL
- (void)getConfigiurationDetailsWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework13Configuration")
@interface Configuration : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Configuration (SWIFT_EXTENSION(CapillaryFramework))
@property (nonatomic, copy) NSString * _Nullable pk;
@property (nonatomic, copy) NSString * _Nullable propertyName;
@property (nonatomic, copy) NSString * _Nullable propertyValue;
@end

@class NSMutableArray;

SWIFT_CLASS("_TtC18CapillaryFramework11ConfigureBO")
@interface ConfigureBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull propertyname;
@property (nonatomic, copy) NSString * _Nonnull propertyvalue;
@property (nonatomic, copy) NSString * _Nonnull pk;
@property (nonatomic, strong) NSMutableArray * _Nullable locationList;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ProductListBO;

SWIFT_CLASS("_TtC18CapillaryFramework19CoreDataAccessLayer")
@interface CoreDataAccessLayer : NSObject
- (NSArray<NSManagedObject *> * _Nullable)getListOfObjectsForEntityForNameWithStrClass:(NSString * _Nonnull)strClass strFetcher:(NSString * _Nonnull)strFetcher SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSManagedObject *> * _Nullable)getListDataForEntityWithStrclass:(NSString * _Nonnull)strclass strFormat:(NSString * _Nonnull)strFormat SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSManagedObject *> * _Nullable)getDataForConfigurationEntityWithStrFetcher:(NSString * _Nonnull)strFetcher SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSManagedObject *> * _Nullable)getDataForCartEntityWithStrFetcher:(NSString * _Nonnull)strFetcher SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getAllConfigurationsCount SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSManagedObject *> * _Nullable)getDataForCategoryMenuEntityWithStrFetcher:(NSString * _Nonnull)strFetcher SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSString *> * _Nullable)getFirstLevelList SWIFT_WARN_UNUSED_RESULT;
- (void)saveAllCategoryObjectWithArrCategory:(NSArray<CategoryBO *> * _Nonnull)arrCategory;
- (NSArray<NSString *> * _Nonnull)getSecondLevelListWithLevel1StringWithStrLevel1:(NSString * _Nonnull)strLevel1 SWIFT_WARN_UNUSED_RESULT;
- (CategoryMenu * _Nullable)getCategoryBOWithIDWithStrID:(NSString * _Nonnull)strID SWIFT_WARN_UNUSED_RESULT;
- (Configuration * _Nullable)getConfigurationWithNameWithStrName:(NSString * _Nonnull)strName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getConfigPropertyWithNameWithStrName:(NSString * _Nonnull)strName SWIFT_WARN_UNUSED_RESULT;
- (void)insertAllConfigurationsWithArrayWithArrConfig:(NSArray<ConfigureBO *> * _Nonnull)arrConfig;
- (NSArray<CartItemBO *> * _Nonnull)getAllProductCartItems SWIFT_WARN_UNUSED_RESULT;
- (NSArray<CartItemBO *> * _Nonnull)getAllBundleItems SWIFT_WARN_UNUSED_RESULT;
- (NSArray<CartItemBO *> * _Nonnull)getAllBundleCartItemsWithLocalRefKeyWithStrKey:(NSString * _Nonnull)strKey SWIFT_WARN_UNUSED_RESULT;
- (NSArray<CartItemBO *> * _Nonnull)getAllBundleCartItems SWIFT_WARN_UNUSED_RESULT;
- (NSArray<CartItemBO *> * _Nonnull)getAllBundleCartItemsWithIDWithLocalRefKey:(NSString * _Nonnull)localRefKey SWIFT_WARN_UNUSED_RESULT;
- (NSArray<CartItemBO *> * _Nonnull)getAllCartItems SWIFT_WARN_UNUSED_RESULT;
- (NSArray<ProductListBO *> * _Nonnull)getAllCartItemsForReOrder SWIFT_WARN_UNUSED_RESULT;
- (void)removeCartItemWithCartItem:(CartItemBO * _Nonnull)cartItem;
- (void)removeAllCartItemsFromLocalDB;
- (NSArray<CartTable *> * _Nonnull)getCartWithParentId:(NSString * _Nonnull)parentId productId:(NSString * _Nonnull)productId SWIFT_WARN_UNUSED_RESULT;
- (NSArray<CartTable *> * _Nonnull)getAllCartItemsWithProductIdWithProductId:(NSString * _Nonnull)productId SWIFT_WARN_UNUSED_RESULT;
- (NSArray<CartTable *> * _Nonnull)getAllCartItemsWithParentIdWithParentId:(NSString * _Nonnull)parentId SWIFT_WARN_UNUSED_RESULT;
- (void)saveCartItemsToLocalDBFromServerWithArr:(NSArray<CartItemBO *> * _Nonnull)arr;
- (NSArray<CartTable *> * _Nonnull)getAllCartProductsWithParentIdWithParentId:(NSString * _Nonnull)parentId variantId:(NSString * _Nonnull)variantId SWIFT_WARN_UNUSED_RESULT;
- (void)removeFailedCartItemsInLocalDBFromServerWithArr:(NSArray<CartItemBO *> * _Nonnull)arr;
- (void)setCartReferenceKeySessionExpiredWithArr:(NSArray<CartItemBO *> * _Nonnull)arr;
- (void)insertProductIntoCartTableWithProduct:(ProductListBO * _Nonnull)product;
- (void)incrementCartCountOfItemsWithProductID:(NSString * _Nonnull)productID variantId:(NSString * _Nonnull)variantId cartCount:(NSInteger)cartCount;
- (void)incrementCartCountOfItemsWithLocalRefKey:(NSString * _Nonnull)localRefKey cartCount:(NSInteger)cartCount;
- (void)insertBundleIntoCartTableWithProduct:(ProductListBO * _Nonnull)product;
- (void)deleteAllCartItems;
- (NSInteger)getTotalCartItems SWIFT_WARN_UNUSED_RESULT;
- (float)getCartTotalPrice SWIFT_WARN_UNUSED_RESULT;
- (NSArray<ProductListBO *> * _Nonnull)convertCartTableArrayToProductListBOArrayWithArr:(NSArray<CartTable *> * _Nonnull)arr SWIFT_WARN_UNUSED_RESULT;
- (NSArray<CartItemBO *> * _Nonnull)convertCartTableArrayToCartItemArrayWithArr:(NSArray<CartTable *> * _Nonnull)arr SWIFT_WARN_UNUSED_RESULT;
- (void)saveContext;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework11CountriesBO")
@interface CountriesBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull locationId;
@property (nonatomic, copy) NSString * _Nonnull locationName;
@property (nonatomic, copy) NSString * _Nonnull countryCode;
@property (nonatomic, copy) NSString * _Nonnull countryId;
@property (nonatomic, copy) NSString * _Nonnull currency;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework9CouponsBO")
@interface CouponsBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull CampaignId;
@property (nonatomic, copy) NSString * _Nonnull CampaignTitle;
@property (nonatomic, copy) NSString * _Nonnull CampaignType;
@property (nonatomic, copy) NSString * _Nonnull VoucherAmount;
@property (nonatomic, copy) NSString * _Nonnull MaxDiscount;
@property (nonatomic, copy) NSString * _Nonnull VoucherCode;
@property (nonatomic) NSInteger RuleId;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework8Customer")
@interface Customer : BaseBL
- (void)loginWithEmailIdWithUsername:(NSString * _Nonnull)username password:(NSString * _Nonnull)password successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)registerUserWithEmailWithFirstName:(NSString * _Nonnull)firstName lastName:(NSString * _Nonnull)lastName email:(NSString * _Nonnull)email mobileNo:(NSString * _Nonnull)mobileNo password:(NSString * _Nonnull)password dob:(NSString * _Nonnull)dob gender:(NSString * _Nonnull)gender userName:(NSString * _Nonnull)userName successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)verifyOTPWithUsername:(NSString * _Nonnull)username password:(NSString * _Nonnull)password otp:(NSString * _Nonnull)otp otpToken:(NSString * _Nonnull)otpToken successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)searchCustomerWithUsername:(NSString * _Nonnull)username successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)validateTokenWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)changePasswordWithUsername:(NSString * _Nonnull)username password:(NSString * _Nonnull)password successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getUserProfileWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)editUserProfileWithObject:(UserProfileBO * _Nonnull)object successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)callLogoutWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)forgotPasswordWithEmail:(NSString * _Nonnull)email successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)resetPasswordServiceWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)contactUsWithName:(NSString * _Nonnull)name email:(NSString * _Nonnull)email phoneNum:(NSString * _Nonnull)phoneNum message:(NSString * _Nonnull)message successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)submitReviewWithCommentWithEmail:(NSString * _Nonnull)email rating:(NSInteger)rating strComment:(NSString * _Nonnull)strComment strCallActionID:(NSString * _Nonnull)strCallActionID successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getAllShippingAddressWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)deleteAddressWithAddressIdWithAddressId:(NSString * _Nonnull)AddressId successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)saveAddressWithBo:(ShipingAddressBO * _Nonnull)bo successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)callPrescriptionCreateLeadWithUrl:(NSString * _Nonnull)Url selectedAddr:(ShipingAddressBO * _Nonnull)selectedAddr strStateName:(NSString * _Nonnull)strStateName prescrption_uploadId:(NSString * _Nonnull)prescrption_uploadId successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TimeSlotsBO;

SWIFT_CLASS("_TtC18CapillaryFramework9DaySlotBO")
@interface DaySlotBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull Day;
@property (nonatomic, copy) NSArray<TimeSlotsBO *> * _Nonnull arrTimeSlots;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework12DeliverySlot")
@interface DeliverySlot : BaseBL
- (void)getDeliverySlotsFromFrontAPIWithDeliveryMode:(NSString * _Nonnull)deliveryMode outputformat:(NSString * _Nonnull)outputformat successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework14FavouriteTable")
@interface FavouriteTable : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface FavouriteTable (SWIFT_EXTENSION(CapillaryFramework))
@property (nonatomic, copy) NSString * _Nullable brand;
@property (nonatomic, strong) NSNumber * _Nullable cartCount;
@property (nonatomic, copy) NSString * _Nullable cat1;
@property (nonatomic, copy) NSString * _Nullable cat2;
@property (nonatomic, copy) NSString * _Nullable cat3;
@property (nonatomic, copy) NSString * _Nullable catalogSequence;
@property (nonatomic, strong) NSNumber * _Nullable hsId;
@property (nonatomic, strong) NSNumber * _Nullable inventory;
@property (nonatomic, strong) NSNumber * _Nullable isExpress;
@property (nonatomic, strong) NSNumber * _Nullable isFavourite;
@property (nonatomic, copy) NSString * _Nullable mrp;
@property (nonatomic, strong) NSNumber * _Nullable productID;
@property (nonatomic, copy) NSString * _Nullable productTitle;
@property (nonatomic, copy) NSString * _Nullable smallImage;
@property (nonatomic, copy) NSString * _Nullable storeId;
@property (nonatomic, copy) NSString * _Nullable variantProperty;
@property (nonatomic, copy) NSString * _Nullable variantValue;
@property (nonatomic, copy) NSString * _Nullable webPrice;
@end


SWIFT_CLASS("_TtC18CapillaryFramework15FeedbackOrderBO")
@interface FeedbackOrderBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull OrderId;
@property (nonatomic, copy) NSString * _Nonnull OrderStatus;
@property (nonatomic, copy) NSString * _Nonnull OrderDate;
@property (nonatomic, copy) NSString * _Nonnull UserId;
@property (nonatomic, copy) NSString * _Nonnull LocationCode;
@property (nonatomic, copy) NSString * _Nonnull LocationId;
@property (nonatomic, copy) NSString * _Nonnull ItemsCount;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class FilterDetailBO;
@class ProductDetailBO;

SWIFT_CLASS("_TtC18CapillaryFramework8FilterBO")
@interface FilterBO : NSObject
@property (nonatomic) NSInteger ProductCount;
@property (nonatomic) NSInteger Rank;
@property (nonatomic, copy) NSString * _Nonnull Name;
@property (nonatomic, copy) NSString * _Nonnull filterId;
@property (nonatomic) BOOL isSelected;
@property (nonatomic) float PriceMax;
@property (nonatomic) float PriceMin;
@property (nonatomic, copy) NSArray<FilterDetailBO *> * _Nonnull arrBrands;
@property (nonatomic, copy) NSArray<FilterDetailBO *> * _Nonnull arrCategories;
@property (nonatomic, copy) NSArray<FilterDetailBO *> * _Nonnull arrPriceRange;
@property (nonatomic, copy) NSArray<FilterDetailBO *> * _Nonnull arrAttributes;
@property (nonatomic, copy) NSArray<FilterDetailBO *> * _Nonnull arrGroups;
@property (nonatomic, copy) NSArray<FilterDetailBO *> * _Nonnull arrProductTags;
@property (nonatomic, copy) NSArray<FilterDetailBO *> * _Nonnull arrSellers;
@property (nonatomic, copy) NSArray<FilterDetailBO *> * _Nonnull arrVariants;
@property (nonatomic, copy) NSArray<ProductDetailBO *> * _Nonnull arrProducts;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework14FilterDetailBO")
@interface FilterDetailBO : NSObject
@property (nonatomic) NSInteger ProductCount;
@property (nonatomic) NSInteger Rank;
@property (nonatomic, copy) NSString * _Nonnull Name;
@property (nonatomic, copy) NSString * _Nonnull filterId;
@property (nonatomic) BOOL isSelected;
@property (nonatomic) float PriceMax;
@property (nonatomic) float PriceMin;
@property (nonatomic, copy) NSString * _Nonnull variantKeyName;
@property (nonatomic, copy) NSString * _Nonnull attributeKeyName;
@property (nonatomic, copy) NSArray<FilterDetailBO *> * _Nonnull arrValues;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework16FrameworkSession")
@interface FrameworkSession : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FrameworkSession * _Nonnull sharedMJSession;)
+ (FrameworkSession * _Nonnull)sharedMJSession SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework8Location")
@interface Location : BaseBL
- (void)getLocationCodeFromDeveloperAPIWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework10LocationBO")
@interface LocationBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull strPincode;
@property (nonatomic, copy) NSString * _Nonnull areaCode;
@property (nonatomic, copy) NSString * _Nonnull areaName;
@property (nonatomic, copy) NSString * _Nonnull strCity;
@property (nonatomic, copy) NSString * _Nonnull strCityID;
@property (nonatomic, copy) NSString * _Nonnull strCountry;
@property (nonatomic, copy) NSString * _Nonnull strCountryCode;
@property (nonatomic, copy) NSString * _Nonnull strDelDistanceArial;
@property (nonatomic, copy) NSString * _Nonnull strDelDistanceRoad;
@property (nonatomic, copy) NSString * _Nonnull strDeliveryMode;
@property (nonatomic, copy) NSString * _Nonnull strDisplayCategories;
@property (nonatomic, copy) NSString * _Nonnull strState;
@property (nonatomic, copy) NSString * _Nonnull strStateCode;
@property (nonatomic, copy) NSString * _Nonnull strType;
@property (nonatomic, copy) NSString * _Nonnull strID;
@property (nonatomic) BOOL isActive;
@property (nonatomic, copy) NSString * _Nonnull strCode;
@property (nonatomic, copy) NSString * _Nonnull strName;
@property (nonatomic, copy) NSString * _Nonnull strDescription;
@property (nonatomic, copy) NSString * _Nonnull strTimeZone;
@property (nonatomic, copy) NSString * _Nonnull strExternId;
@property (nonatomic, copy) NSString * _Nonnull strCurrId;
@property (nonatomic, copy) NSString * _Nonnull strLangId;
@property (nonatomic, copy) NSString * _Nonnull strLastUpdatedBy;
@property (nonatomic, strong) NSDate * _Nonnull strLastUpdatedOn;
@property (nonatomic, copy) NSString * _Nonnull strMobile;
@property (nonatomic, copy) NSString * _Nonnull strLandLine;
@property (nonatomic, copy) NSString * _Nonnull strEmail;
@property (nonatomic, copy) NSString * _Nonnull strLangCode;
@property (nonatomic, copy) NSString * _Nonnull strAddress;
@property (nonatomic, copy) NSString * _Nonnull strLangLocale;
@property (nonatomic) float lattitude;
@property (nonatomic) float longitude;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSData;

SWIFT_CLASS("_TtC18CapillaryFramework8Merchant")
@interface Merchant : BaseBL
- (void)generateImageUploadURLWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)uploadImageWithDataWithImageData:(NSData * _Nonnull)imageData urlString:(NSString * _Nonnull)urlString imageName:(NSString * _Nonnull)imageName successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface NSString (SWIFT_EXTENSION(CapillaryFramework))
@end


SWIFT_CLASS("_TtC18CapillaryFramework11Navigations")
@interface Navigations : BaseBL
- (void)getallCategoryMenuWithRefcode:(NSString * _Nonnull)refcode successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework17NotificationTable")
@interface NotificationTable : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface NotificationTable (SWIFT_EXTENSION(CapillaryFramework))
@property (nonatomic, copy) NSString * _Nullable imageurl;
@property (nonatomic, strong) NSNumber * _Nullable isNewNotification;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable productId;
@property (nonatomic, copy) NSString * _Nullable type;
@end


SWIFT_CLASS("_TtC18CapillaryFramework5Order")
@interface Order : BaseBL
- (void)placeorderWithPaymentOption:(NSString * _Nonnull)paymentOption paymentType:(NSString * _Nonnull)paymentType gateWayId:(NSString * _Nonnull)gateWayId successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)lastOrderInfoWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)GetOrderInfoWithBundleItemsWithStrOrderId:(NSInteger)strOrderId successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)GetOrderInfoWithOrderIdWithStrOrderId:(NSInteger)strOrderId successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)GetOrderDetailWithOrderIDWithStrOrderId:(NSInteger)strOrderId successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getOrderHistoryWithStatusWithStatus:(NSString * _Nonnull)Status from:(NSInteger)from To:(NSInteger)To todate:(NSString * _Nonnull)todate successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)AuthoriseOrderWithOrderId:(NSString * _Nonnull)orderId dateTime:(NSString * _Nonnull)dateTime successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)cancelOrderWithOrderIDWithOrderId:(NSString * _Nonnull)orderId pgResponce:(NSString * _Nonnull)pgResponce successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)saveOrderFeedBackWithOrderId:(NSString * _Nonnull)orderId rating:(NSInteger)rating strComment:(NSString * _Nonnull)strComment successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getOrdersForFeedBackFromDate:(NSString * _Nonnull)fromDate toDate:(NSString * _Nonnull)toDate successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class OrderDetailListBO;
@class OrderDetailBO;

SWIFT_CLASS("_TtC18CapillaryFramework7OrderBO")
@interface OrderBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull OrderDate;
@property (nonatomic) BOOL isSelected;
@property (nonatomic) BOOL isReOrderSelected;
@property (nonatomic, copy) NSString * _Nonnull OrderId;
@property (nonatomic, copy) NSString * _Nonnull AmountPayable;
@property (nonatomic, copy) NSString * _Nonnull BillAddress1;
@property (nonatomic, copy) NSString * _Nonnull BillAddress2;
@property (nonatomic, copy) NSString * _Nonnull BillCity;
@property (nonatomic, copy) NSString * _Nonnull BillCountry;
@property (nonatomic, copy) NSString * _Nonnull BillEmail;
@property (nonatomic, copy) NSString * _Nonnull BillFirstname;
@property (nonatomic, copy) NSString * _Nonnull BillLastname;
@property (nonatomic, copy) NSString * _Nonnull BillMobile;
@property (nonatomic, copy) NSString * _Nonnull BillPhone;
@property (nonatomic, copy) NSString * _Nonnull BillZIP;
@property (nonatomic, copy) NSString * _Nonnull BillingState;
@property (nonatomic, copy) NSString * _Nonnull ConversionFactor;
@property (nonatomic, copy) NSString * _Nonnull DeliveryOption;
@property (nonatomic, copy) NSString * _Nonnull IsGift;
@property (nonatomic, copy) NSString * _Nonnull LeadTime;
@property (nonatomic, copy) NSString * _Nonnull MerchantId;
@property (nonatomic, copy) NSString * _Nonnull OrderLineId;
@property (nonatomic, copy) NSString * _Nonnull PromotionDiscount;
@property (nonatomic, copy) NSString * _Nonnull Rewards;
@property (nonatomic, copy) NSString * _Nonnull ShipAddress1;
@property (nonatomic, copy) NSString * _Nonnull ShipAddress2;
@property (nonatomic, copy) NSString * _Nonnull ShipCity;
@property (nonatomic, copy) NSString * _Nonnull ShipCountry;
@property (nonatomic, copy) NSString * _Nonnull ShipEmail;
@property (nonatomic, copy) NSString * _Nonnull ShipFirstname;
@property (nonatomic, copy) NSString * _Nonnull ShipLastname;
@property (nonatomic, copy) NSString * _Nonnull ShipMobile;
@property (nonatomic, copy) NSString * _Nonnull ShipOtherCity;
@property (nonatomic, copy) NSString * _Nonnull ShipPhone;
@property (nonatomic, copy) NSString * _Nonnull ShipState;
@property (nonatomic, copy) NSString * _Nonnull ShipZip;
@property (nonatomic, copy) NSString * _Nonnull ShippingDiscount;
@property (nonatomic, copy) NSString * _Nonnull Status;
@property (nonatomic, copy) NSString * _Nonnull SupplierID;
@property (nonatomic, copy) NSString * _Nonnull TAXTotal;
@property (nonatomic, copy) NSString * _Nonnull VoucherDiscount;
@property (nonatomic, copy) NSString * _Nonnull TotalAmount;
@property (nonatomic, copy) NSString * _Nonnull UserId;
@property (nonatomic, copy) NSString * _Nonnull VocuherDiscount;
@property (nonatomic, copy) NSString * _Nonnull VoucherCode;
@property (nonatomic, copy) NSString * _Nonnull cpuserid;
@property (nonatomic, copy) NSString * _Nonnull shipdate;
@property (nonatomic, copy) NSString * _Nonnull sku;
@property (nonatomic, copy) NSString * _Nonnull deliverySlotEndTime;
@property (nonatomic, copy) NSString * _Nonnull deliverySlotStartTime;
@property (nonatomic, copy) NSArray<OrderDetailListBO *> * _Nonnull arrOrderProducts;
@property (nonatomic, copy) NSArray<OrderDetailBO *> * _Nonnull arrOrderLineProducts;
@property (nonatomic) BOOL isOPen;
@property (nonatomic, copy) NSString * _Nonnull demandedDate;
@property (nonatomic, copy) NSString * _Nonnull PaymentOption;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework13OrderDetailBO")
@interface OrderDetailBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull OrderLineId;
@property (nonatomic, copy) NSString * _Nonnull OrderId;
@property (nonatomic, copy) NSString * _Nonnull ProductId;
@property (nonatomic, copy) NSString * _Nonnull variantProductId;
@property (nonatomic, copy) NSString * _Nonnull IsParentProduct;
@property (nonatomic, copy) NSString * _Nonnull Description;
@property (nonatomic, copy) NSString * _Nonnull Quantity;
@property (nonatomic, copy) NSString * _Nonnull ShippingCost;
@property (nonatomic, copy) NSString * _Nonnull ProductPrice;
@property (nonatomic, copy) NSString * _Nonnull TotalPromotionDiscount;
@property (nonatomic, copy) NSString * _Nonnull ReturnReason;
@property (nonatomic, copy) NSString * _Nonnull ReturnQty;
@property (nonatomic, copy) NSString * _Nonnull IsBackOrder;
@property (nonatomic, copy) NSString * _Nonnull TotalVoucherDiscount;
@property (nonatomic, copy) NSString * _Nonnull TotalTaxAmount;
@property (nonatomic, copy) NSString * _Nonnull DeliveryMode;
@property (nonatomic, copy) NSString * _Nonnull ShippingVoucherDiscount;
@property (nonatomic, copy) NSString * _Nonnull variantMasterProductId;
@property (nonatomic, copy) NSString * _Nonnull ShippingStatus;
@property (nonatomic, copy) NSString * _Nonnull VendorId;
@property (nonatomic, copy) NSString * _Nonnull SKU;
@property (nonatomic, copy) NSString * _Nonnull variantSku;
@property (nonatomic, copy) NSString * _Nonnull ProductTitle;
@property (nonatomic, copy) NSString * _Nonnull smallimage;
@property (nonatomic, copy) NSString * _Nonnull variantValue;
@property (nonatomic) NSInteger cartCount;
@property (nonatomic) BOOL isCartSelected;
@property (nonatomic) BOOL isCheckMarkSelected;
@property (nonatomic) BOOL isSelected;
@property (nonatomic, copy) NSString * _Nonnull ItemStatus;
@property (nonatomic, copy) NSString * _Nonnull ImageUrl;
@property (nonatomic, copy) NSString * _Nonnull LocationCode;
@property (nonatomic, copy) NSString * _Nonnull BundleProductId;
@property (nonatomic, copy) NSString * _Nonnull ParentReDetailsId;
@property (nonatomic, copy) NSString * _Nonnull Portion;
@property (nonatomic, copy) NSString * _Nonnull MRP;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework17OrderDetailListBO")
@interface OrderDetailListBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull OrderLineId;
@property (nonatomic, copy) NSString * _Nonnull OrderId;
@property (nonatomic, copy) NSString * _Nonnull ProductId;
@property (nonatomic, copy) NSString * _Nonnull ProductTitle;
@property (nonatomic, copy) NSString * _Nonnull ImageUrl;
@property (nonatomic) BOOL IsBundleProduct;
@property (nonatomic, copy) NSArray<OrderDetailBO *> * _Nonnull arrBundleProducts;
@property (nonatomic, copy) NSString * _Nonnull Description;
@property (nonatomic, copy) NSString * _Nonnull Quantity;
@property (nonatomic, copy) NSString * _Nonnull ShippingCost;
@property (nonatomic, copy) NSString * _Nonnull WebPrice;
@property (nonatomic, copy) NSString * _Nonnull MRP;
@property (nonatomic, copy) NSString * _Nonnull locationCode;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework16PaymentOptionsBO")
@interface PaymentOptionsBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull GatewayId;
@property (nonatomic, copy) NSString * _Nonnull GatewayTitle;
@property (nonatomic, copy) NSString * _Nonnull PaymentType;
@property (nonatomic, copy) NSString * _Nonnull Paymentoption;
@property (nonatomic, copy) NSString * _Nonnull SupplierId;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework7Product")
@interface Product : BaseBL
- (void)getProductReviewWithProductId:(NSString * _Nonnull)ProductId successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getProductDetailWithProductid:(NSString * _Nonnull)productid successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getAllProductsWithCatBO:(CategoryBO * _Nonnull)catBO from:(NSInteger)from brandId:(NSString * _Nonnull)brandId tag:(NSString * _Nonnull)tag to:(NSInteger)to successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)submitReviewWithProductidWithProductId:(NSString * _Nonnull)productId rating:(NSInteger)rating strTitle:(NSString * _Nonnull)strTitle strMessage:(NSString * _Nonnull)strMessage successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)compareCategoriesWithArrProductIds:(NSArray<NSNumber *> * _Nonnull)arrProductIds successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getRelatedProductsOrSimilarForProductWithIDWithProductID:(NSString * _Nonnull)productID withTag:(NSString * _Nonnull)withTag successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework15ProductDetailBO")
@interface ProductDetailBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull storeid;
@property (nonatomic, copy) NSString * _Nonnull productid;
@property (nonatomic) NSInteger hsid;
@property (nonatomic, copy) NSString * _Nonnull brand;
@property (nonatomic, copy) NSString * _Nonnull brandid;
@property (nonatomic, copy) NSString * _Nonnull deliverymode;
@property (nonatomic, copy) NSString * _Nonnull hierarchy1category;
@property (nonatomic, copy) NSString * _Nonnull hierarchy2category;
@property (nonatomic, copy) NSString * _Nonnull hierarchy3category;
@property (nonatomic, copy) NSString * _Nonnull hierarchy4category;
@property (nonatomic, copy) NSString * _Nonnull hierarchy1categoryID;
@property (nonatomic, copy) NSString * _Nonnull hierarchy2categoryID;
@property (nonatomic, copy) NSString * _Nonnull hierarchy3categoryID;
@property (nonatomic, copy) NSString * _Nonnull hierarchy4categoryID;
@property (nonatomic) NSInteger inventory;
@property (nonatomic, copy) NSString * _Nonnull largeimage;
@property (nonatomic, copy) NSString * _Nonnull longdescription;
@property (nonatomic, copy) NSString * _Nonnull mrp;
@property (nonatomic, copy) NSString * _Nonnull producttitle;
@property (nonatomic, copy) NSString * _Nonnull shortdescription;
@property (nonatomic, copy) NSString * _Nonnull smallimage;
@property (nonatomic, copy) NSString * _Nonnull variantproperty;
@property (nonatomic, copy) NSString * _Nonnull sharelink;
@property (nonatomic, copy) NSString * _Nonnull variantvalue;
@property (nonatomic, copy) NSString * _Nonnull variantID;
@property (nonatomic, copy) NSString * _Nonnull webprice;
@property (nonatomic, copy) NSString * _Nonnull relatedhsid;
@property (nonatomic, copy) NSString * _Nonnull relatedproductid;
@property (nonatomic, copy) NSString * _Nonnull h3catname;
@property (nonatomic, copy) NSString * _Nonnull h2catname;
@property (nonatomic, copy) NSString * _Nonnull h1catname;
@property (nonatomic, copy) NSArray<ProductListBO *> * _Nonnull arrVarients;
@property (nonatomic) BOOL isExpress;
@property (nonatomic) NSInteger cartCount;
@property (nonatomic, copy) NSString * _Nonnull discount;
@property (nonatomic, copy) NSString * _Nonnull price;
@property (nonatomic, copy) NSString * _Nonnull sku;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nonnull multipleImages;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nonnull attributes;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nonnull variantProperties;
@property (nonatomic, copy) NSString * _Nonnull productType;
@property (nonatomic, copy) NSString * _Nonnull offerDescription;
@property (nonatomic, copy) NSString * _Nonnull tags;
@property (nonatomic) NSInteger attributeCount;
@property (nonatomic, copy) NSArray<BundleGroupBO *> * _Nonnull BundleGroups;
@property (nonatomic) BOOL isSelected;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull varients;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull variantProducts;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework13ProductListBO")
@interface ProductListBO : NSObject <NSCopying>
@property (nonatomic) NSInteger listQunatity;
@property (nonatomic) NSInteger cartCount;
@property (nonatomic, copy) NSString * _Nonnull productType;
@property (nonatomic, copy) NSString * _Nonnull storeid;
@property (nonatomic, copy) NSString * _Nonnull webprice;
@property (nonatomic, copy) NSString * _Nonnull dealId;
@property (nonatomic, copy) NSString * _Nonnull parentId;
@property (nonatomic, copy) NSString * _Nonnull productid;
@property (nonatomic) NSInteger hsid;
@property (nonatomic, copy) NSString * _Nonnull brand;
@property (nonatomic, copy) NSString * _Nonnull brandid;
@property (nonatomic) NSInteger inventory;
@property (nonatomic, copy) NSString * _Nonnull mrp;
@property (nonatomic, copy) NSString * _Nonnull producttitle;
@property (nonatomic, copy) NSString * _Nonnull smallimage;
@property (nonatomic, copy) NSString * _Nonnull variantproperty;
@property (nonatomic, copy) NSString * _Nonnull variantvalue;
@property (nonatomic, copy) NSString * _Nonnull relatedVariantProductID;
@property (nonatomic) NSInteger attributeCount;
@property (nonatomic, copy) NSString * _Nonnull variantProductId;
@property (nonatomic, copy) NSString * _Nonnull HcatName1;
@property (nonatomic, copy) NSString * _Nonnull HcatName2;
@property (nonatomic, copy) NSString * _Nonnull HcatName3;
@property (nonatomic, copy) NSString * _Nonnull cat1;
@property (nonatomic, copy) NSString * _Nonnull cat2;
@property (nonatomic, copy) NSString * _Nonnull cat3;
@property (nonatomic, copy) NSString * _Nonnull discount;
@property (nonatomic, copy) NSString * _Nonnull shortdescription;
@property (nonatomic, copy) NSString * _Nonnull longDescription;
@property (nonatomic, copy) NSString * _Nonnull largeimage;
@property (nonatomic, copy) NSString * _Nonnull localReferenceKey;
@property (nonatomic, copy) NSString * _Nonnull h2catname;
@property (nonatomic, copy) NSString * _Nonnull h1catname;
@property (nonatomic) BOOL isExpress;
@property (nonatomic) BOOL isCartSelected;
@property (nonatomic) BOOL isCheckMarkSelected;
@property (nonatomic, copy) NSString * _Nonnull sku;
@property (nonatomic, copy) NSString * _Nonnull tagID;
@property (nonatomic, copy) NSString * _Nonnull tags;
@property (nonatomic, copy) NSString * _Nonnull offerDescription;
@property (nonatomic, copy) NSString * _Nonnull CartReferenceKey;
@property (nonatomic, copy) NSString * _Nonnull shoppingList;
@property (nonatomic, copy) NSString * _Nonnull margin;
@property (nonatomic, copy) NSString * _Nonnull deliveryMode;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(ProductListBO * _Nonnull)model OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC18CapillaryFramework10ProductsBO")
@interface ProductsBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull minprice;
@property (nonatomic, copy) NSString * _Nonnull maxprice;
@property (nonatomic, copy) NSString * _Nonnull paging;
@property (nonatomic, copy) NSString * _Nonnull isLastPage;
@property (nonatomic, copy) NSArray<ProductListBO *> * _Nonnull arrProductlist;
@property (nonatomic) NSInteger productCount;
@property (nonatomic, copy) NSString * _Nonnull H2CatName;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework8ReviewBO")
@interface ReviewBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull UserId;
@property (nonatomic, copy) NSString * _Nonnull UserName;
@property (nonatomic, copy) NSString * _Nonnull ProductTitle;
@property (nonatomic, copy) NSString * _Nonnull ReviewTitle;
@property (nonatomic, copy) NSString * _Nonnull ReviewDescription;
@property (nonatomic, copy) NSString * _Nonnull CreatedDateTime;
@property (nonatomic) NSInteger Rating;
@property (nonatomic, copy) NSString * _Nonnull IsGoLive;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework6Search")
@interface Search : BaseBL
- (void)searchProductsWithTextWithStrText:(NSString * _Nonnull)strText categoryId:(NSString * _Nonnull)categoryId from:(NSString * _Nonnull)from brandids:(NSString * _Nonnull)brandids limit:(NSString * _Nonnull)limit IsRefine:(BOOL)IsRefine minprice:(NSString * _Nonnull)minprice maxprice:(NSString * _Nonnull)maxprice variantpropertyids:(NSString * _Nonnull)variantpropertyids attributeValueids:(NSString * _Nonnull)attributeValueids supplierids:(NSString * _Nonnull)supplierids IsExcludeCategories:(BOOL)IsExcludeCategories groupids:(NSString * _Nonnull)groupids successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)autoSearchProductsWithText:(NSString * _Nonnull)strText categoryid:(NSString * _Nonnull)categoryid limit:(NSString * _Nonnull)limit IsExcludeCategories:(BOOL)IsExcludeCategories successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getFilterCategoriesWithCategoryid:(NSString * _Nonnull)categoryid from:(NSString * _Nonnull)from brandids:(NSString * _Nonnull)brandids maxPrice:(NSString * _Nonnull)maxPrice minPrice:(NSString * _Nonnull)minPrice queryText:(NSString * _Nonnull)queryText isRefine:(BOOL)isRefine isSeachText:(NSString * _Nonnull)isSeachText attributeString:(NSString * _Nonnull)attributeString variantsString:(NSString * _Nonnull)variantsString supplierids:(NSString * _Nonnull)supplierids groupids:(NSString * _Nonnull)groupids variantpropertyids:(NSString * _Nonnull)variantpropertyids limit:(NSString * _Nonnull)limit IsExcludeCategories:(BOOL)IsExcludeCategories successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework16ShipingAddressBO")
@interface ShipingAddressBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull shippingaddressid;
@property (nonatomic, copy) NSString * _Nonnull userId;
@property (nonatomic, copy) NSString * _Nonnull firstname;
@property (nonatomic, copy) NSString * _Nonnull lastname;
@property (nonatomic, copy) NSString * _Nonnull address1;
@property (nonatomic, copy) NSString * _Nonnull address2;
@property (nonatomic, copy) NSString * _Nonnull state;
@property (nonatomic, copy) NSString * _Nonnull stateId;
@property (nonatomic, copy) NSString * _Nonnull pin;
@property (nonatomic, copy) NSString * _Nonnull countrycode;
@property (nonatomic, copy) NSString * _Nonnull countryId;
@property (nonatomic, copy) NSString * _Nonnull citycode;
@property (nonatomic, copy) NSString * _Nonnull cityId;
@property (nonatomic, copy) NSString * _Nonnull phoneno;
@property (nonatomic, copy) NSString * _Nonnull mobileno;
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic, copy) NSString * _Nonnull othercity;
@property (nonatomic, copy) NSString * _Nonnull landmark;
@property (nonatomic, copy) NSString * _Nonnull countryName;
@property (nonatomic, copy) NSString * _Nonnull stateName;
@property (nonatomic, copy) NSString * _Nonnull cityName;
@property (nonatomic) BOOL isSelected;
@property (nonatomic, copy) NSString * _Nonnull shipTelephone;
@property (nonatomic, copy) NSString * _Nonnull shipEmail;
@property (nonatomic, copy) NSString * _Nonnull shipTelephoneCode;
@property (nonatomic, copy) NSString * _Nonnull billTelephone;
@property (nonatomic, copy) NSString * _Nonnull billTelephoneCode;
@property (nonatomic, copy) NSString * _Nonnull billMobileCode;
@property (nonatomic) BOOL isShippingAddressDifferent;
@property (nonatomic, copy) NSString * _Nonnull shipMobileCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework16ShippingOptionBO")
@interface ShippingOptionBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull ShippingMode;
@property (nonatomic, copy) NSString * _Nonnull ShippingModeId;
@property (nonatomic, copy) NSString * _Nonnull SupplierId;
@property (nonatomic) BOOL isselected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework12ShoppingList")
@interface ShoppingList : BaseBL
- (void)getShoppingListFromFrontAPIWithListType:(NSString * _Nonnull)listType defaultShoppingList:(BOOL)defaultShoppingList uri:(NSString * _Nonnull)uri successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getGlobalShoppingListWithShoppinglistId:(NSString * _Nonnull)shoppinglistId defaultShoppingList:(BOOL)defaultShoppingList uri:(NSString * _Nonnull)uri successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)setShoppingListWithListName:(NSString * _Nonnull)listName refCode:(NSString * _Nonnull)refCode successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)deleteShoppinglistWithIdWithListId:(NSString * _Nonnull)listId successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)addProductToShoppingListsOrDeleteProductInShoppingListWithListId:(NSString * _Nonnull)listId withProductId:(NSString * _Nonnull)productId withVariantId:(NSString * _Nonnull)variantId withQuantity:(NSString * _Nonnull)quantity isStatus:(NSString * _Nonnull)isStatus IsSelected:(BOOL)IsSelected successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)addAllProductToShoppingListsOrDeleteAllProductInShoppingListWithProducts:(NSArray<ProductListBO *> * _Nonnull)products withShoppingList:(NSString * _Nonnull)listId isStatus:(NSString * _Nonnull)isStatus successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework14ShoppingListBO")
@interface ShoppingListBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull shopingListId;
@property (nonatomic, copy) NSString * _Nonnull listName;
@property (nonatomic, copy) NSString * _Nonnull privacyLevel;
@property (nonatomic, copy) NSString * _Nonnull userId;
@property (nonatomic, copy) NSString * _Nonnull merchantId;
@property (nonatomic, copy) NSString * _Nonnull createdDate;
@property (nonatomic, copy) NSString * _Nonnull modifiedDate;
@property (nonatomic) NSInteger userGroupId;
@property (nonatomic, copy) NSString * _Nonnull allowUserToAddItems;
@property (nonatomic, copy) NSString * _Nonnull displayingMyAccount;
@property (nonatomic, copy) NSString * _Nonnull createdBy;
@property (nonatomic, copy) NSString * _Nonnull refCode;
@property (nonatomic, copy) NSArray<ProductListBO *> * _Nonnull items;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework10SideMenuBO")
@interface SideMenuBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull strType;
@property (nonatomic, copy) NSString * _Nonnull strValue;
@property (nonatomic) BOOL isSelected;
@property (nonatomic, copy) NSString * _Nonnull strID;
@property (nonatomic) NSInteger displaySequence;
@property (nonatomic, copy) NSArray<ProductListBO *> * _Nonnull arrSubCategories;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework5Store")
@interface Store : BaseBL
- (void)getAllCountriesWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getAllStatesByCountryIdWithCountryId:(NSString * _Nonnull)countryId successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getAllCitiesByStateIdWithStateId:(NSString * _Nonnull)stateId successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getAllStoresWithSuccessMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getStoresWithPincodeWithStrPinCode:(NSString * _Nonnull)strPinCode successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (void)getNearestLocationsWithLatitude:(NSString * _Nonnull)latitude logitute:(NSString * _Nonnull)logitute successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework14StoreAddressBO")
@interface StoreAddressBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull LocationCode;
@property (nonatomic, copy) NSString * _Nonnull lastname;
@property (nonatomic, copy) NSString * _Nonnull LocationName;
@property (nonatomic, copy) NSString * _Nonnull Address1;
@property (nonatomic, copy) NSString * _Nonnull Address2;
@property (nonatomic, copy) NSString * _Nonnull City;
@property (nonatomic, copy) NSString * _Nonnull Area;
@property (nonatomic, copy) NSString * _Nonnull State;
@property (nonatomic, copy) NSString * _Nonnull Country;
@property (nonatomic, copy) NSString * _Nonnull Pin;
@property (nonatomic, copy) NSString * _Nonnull Contact1;
@property (nonatomic, copy) NSString * _Nonnull Contact2;
@property (nonatomic, copy) NSString * _Nonnull Description;
@property (nonatomic, copy) NSString * _Nonnull Latitude;
@property (nonatomic, copy) NSString * _Nonnull Longitude;
@property (nonatomic, copy) NSString * _Nonnull LocationType;
@property (nonatomic, copy) NSString * _Nonnull IsDistributionCenter;
@property (nonatomic, copy) NSString * _Nonnull EmailId;
@property (nonatomic, copy) NSString * _Nonnull IsParticipateInStock;
@property (nonatomic, copy) NSString * _Nonnull IsDefaultLocation;
@property (nonatomic, copy) NSString * _Nonnull IsOfflinneCheckoutEnabled;
@property (nonatomic, copy) NSString * _Nonnull IsPointOfSale;
@property (nonatomic, copy) NSString * _Nonnull IsOfflineDeals;
@property (nonatomic, copy) NSString * _Nonnull StoreOnTime;
@property (nonatomic, copy) NSString * _Nonnull StoreOffTime;
@property (nonatomic, copy) NSString * _Nonnull StoreOnline;
@property (nonatomic, copy) NSString * _Nonnull IsInStorePickup;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework8StoresBO")
@interface StoresBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull address1;
@property (nonatomic, copy) NSString * _Nonnull address2;
@property (nonatomic, copy) NSString * _Nonnull address3;
@property (nonatomic, copy) NSString * _Nonnull address4;
@property (nonatomic, copy) NSString * _Nonnull area_code;
@property (nonatomic, copy) NSString * _Nonnull area_name;
@property (nonatomic, copy) NSString * _Nonnull city_code;
@property (nonatomic, copy) NSString * _Nonnull city_name;
@property (nonatomic, copy) NSString * _Nonnull country_code;
@property (nonatomic, copy) NSString * _Nonnull country_name;
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic) BOOL is24hrs;
@property (nonatomic, copy) NSString * _Nonnull lattitude;
@property (nonatomic, copy) NSString * _Nonnull longitude;
@property (nonatomic, copy) NSString * _Nonnull mobile;
@property (nonatomic, copy) NSString * _Nonnull phone;
@property (nonatomic, copy) NSString * _Nonnull state_code;
@property (nonatomic, copy) NSString * _Nonnull state_name;
@property (nonatomic, copy) NSString * _Nonnull store_name;
@property (nonatomic) double distance;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC18CapillaryFramework11TimeSlotsBO")
@interface TimeSlotsBO : NSObject
@property (nonatomic, copy) NSString * _Nonnull FormatedSlotRange;
@property (nonatomic, copy) NSString * _Nonnull FormatedDate;
@property (nonatomic, copy) NSString * _Nonnull DeliveryDate;
@property (nonatomic, copy) NSString * _Nonnull DeliverySlotDate;
@property (nonatomic, copy) NSString * _Nonnull DeliverySlotID;
@property (nonatomic, copy) NSString * _Nonnull MerchantID;
@property (nonatomic, copy) NSString * _Nonnull StartTime;
@property (nonatomic, copy) NSString * _Nonnull EndTime;
@property (nonatomic, copy) NSString * _Nonnull LeadTime;
@property (nonatomic, copy) NSString * _Nonnull Intervel;
@property (nonatomic, copy) NSString * _Nonnull MaxOrders;
@property (nonatomic) BOOL Status;
@property (nonatomic) BOOL IsDisabled;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSCoder;

SWIFT_CLASS("_TtC18CapillaryFramework13UserProfileBO")
@interface UserProfileBO : NSObject <NSCoding>
@property (nonatomic, copy) NSString * _Nonnull UserInfoId;
@property (nonatomic, copy) NSString * _Nonnull UserId;
@property (nonatomic, copy) NSString * _Nonnull MerchantId;
@property (nonatomic, copy) NSString * _Nonnull UserName;
@property (nonatomic, copy) NSString * _Nonnull FirstName;
@property (nonatomic, copy) NSString * _Nonnull LastName;
@property (nonatomic, copy) NSString * _Nonnull PostalAddress;
@property (nonatomic, copy) NSString * _Nonnull AlternateEmail;
@property (nonatomic, copy) NSString * _Nonnull City;
@property (nonatomic, copy) NSString * _Nonnull Pin;
@property (nonatomic, copy) NSString * _Nonnull State;
@property (nonatomic, copy) NSString * _Nonnull Country;
@property (nonatomic, copy) NSString * _Nonnull PhoneNo;
@property (nonatomic, copy) NSString * _Nonnull Street;
@property (nonatomic, copy) NSString * _Nonnull MobileNo;
@property (nonatomic, copy) NSString * _Nonnull BirthDate;
@property (nonatomic, copy) NSString * _Nonnull Gender;
@property (nonatomic, copy) NSString * _Nonnull Occupation;
@property (nonatomic, copy) NSString * _Nonnull Industry;
@property (nonatomic, copy) NSString * _Nonnull OtherArea;
@property (nonatomic, copy) NSString * _Nonnull CountryName;
@property (nonatomic, copy) NSString * _Nonnull StateName;
@property (nonatomic, copy) NSString * _Nonnull CityName;
@property (nonatomic, copy) NSString * _Nonnull AreaName;
@property (nonatomic, copy) NSString * _Nonnull OtherCity;
@property (nonatomic) BOOL IsReceiveOffers;
@property (nonatomic, copy) NSString * _Nonnull Password;
@property (nonatomic, copy) NSString * _Nonnull ConfirmPassword;
@property (nonatomic, copy) NSString * _Nonnull Countries;
@property (nonatomic, copy) NSString * _Nonnull States;
@property (nonatomic, copy) NSString * _Nullable IsMobileMapped;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nonnull arrcustomFields;
@property (nonatomic) BOOL isSelected;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC18CapillaryFramework7Voucher")
@interface Voucher : BaseBL
- (void)getAllVouchersWithIsAllVouchers:(BOOL)isAllVouchers successMessage:(void (^ _Nonnull)(id _Nonnull))successMessage failureMessage:(void (^ _Nonnull)(id _Nonnull))failureMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
